// Generates src/internal/generated/component-tokens.ts from the component CSS and
// rewrites the value column of every SPEC.md token table to match.
//
// A component token's value is declared once, in its CSS. Docs pages and SPEC.md
// must never restate it -- run `npm run generate:tokens` after changing a token.

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const COMPONENTS_DIR = join(ROOT, 'src', 'lib', 'components');

// Returns the contents of the first `[data-theme] { ... }` block, which is where
// each component declares its own token defaults. Later blocks are variant
// overrides (e.g. `.button--outline`) and must not be treated as defaults.
function firstDataThemeBlock(css) {
	const start = css.search(/\[data-theme[^\]]*\]\s*\{/);
	if (start === -1) return null;
	const open = css.indexOf('{', start);
	let depth = 0;
	for (let i = open; i < css.length; i++) {
		if (css[i] === '{') depth++;
		else if (css[i] === '}') {
			depth--;
			if (depth === 0) return css.slice(open + 1, i);
		}
	}
	return null;
}

// component folder -> { '--token': 'value' }
function extractComponentTokens() {
	const folders = readdirSync(COMPONENTS_DIR, { withFileTypes: true })
		.filter((d) => d.isDirectory())
		.map((d) => d.name);

	const byComponent = {};

	for (const folder of folders) {
		const folderPath = join(COMPONENTS_DIR, folder);
		const cssFiles = readdirSync(folderPath).filter((f) => f.endsWith('.css'));
		if (cssFiles.length === 0) continue;

		// Read the folder's own stylesheet first so it wins on any name collision.
		cssFiles.sort((a, b) => (a === `${folder}.css` ? -1 : b === `${folder}.css` ? 1 : 0));

		const tokens = {};
		for (const file of cssFiles) {
			const block = firstDataThemeBlock(readFileSync(join(folderPath, file), 'utf-8'));
			if (!block) continue;
			for (const match of block.matchAll(/(--[a-z0-9-]+):\s*([^;]+);/g)) {
				const name = match[1];
				if (name in tokens) continue;
				tokens[name] = match[2]
					.replace(/\s+/g, ' ')
					.replace(/\(\s+/g, '(')
					.replace(/\s+\)/g, ')')
					.trim();
			}
		}

		if (Object.keys(tokens).length > 0) byComponent[folder] = tokens;
	}

	return byComponent;
}

// Emitted for the docs site: token values live in CSS, so docs pages declare
// only `[token, description]` and read the value from here.
function writeGeneratedTokenModule(byComponent) {
	const outDir = join(ROOT, 'src', 'internal', 'generated');
	mkdirSync(outDir, { recursive: true });

	const body = Object.keys(byComponent)
		.sort()
		.map((component) => {
			const rows = Object.entries(byComponent[component])
				.map(([name, value]) => `\t\t'${name}': ${JSON.stringify(value)}`)
				.join(',\n');
			return `\t'${component}': {\n${rows}\n\t}`;
		})
		.join(',\n');

	const file = `// GENERATED by scripts/generate-tokens.js -- do not edit.
// Run \`npm run generate:tokens\` to regenerate from the component CSS.

export const componentTokens: Record<string, Record<string, string>> = {
${body}
};
`;

	writeFileSync(join(outDir, 'component-tokens.ts'), file);
}

// SPEC.md token tables restate values that live in the component CSS, so rewrite
// the value column from the CSS on every run. Descriptions and row order are
// hand-written and left untouched; a row naming an unknown token is reported.
function syncSpecTokenTables(byComponent) {
	let rewritten = 0;
	const unknown = [];

	for (const [folder, tokens] of Object.entries(byComponent)) {
		const specPath = join(COMPONENTS_DIR, folder, 'SPEC.md');
		if (!existsSync(specPath)) continue;

		const before = readFileSync(specPath, 'utf-8');
		const after = before.replace(
			/^(\|\s*`(--[a-z0-9-]+)`\s*\|\s*)`[^`]*`/gm,
			(match, prefix, name) => {
				if (!(name in tokens)) {
					unknown.push(`${folder}/${name}`);
					return match;
				}
				return `${prefix}\`${tokens[name]}\``;
			}
		);

		if (after !== before) {
			writeFileSync(specPath, after);
			rewritten++;
		}
	}

	console.log(`  Synced token values in ${rewritten} SPEC.md files`);
	if (unknown.length > 0) {
		console.warn(`  WARNING: ${unknown.length} SPEC.md rows name tokens absent from CSS:`);
		for (const u of unknown) console.warn(`    ${u}`);
	}
}

function main() {
	console.log('Generating component tokens from CSS...');

	const byComponent = extractComponentTokens();
	const count = Object.values(byComponent).reduce((n, t) => n + Object.keys(t).length, 0);
	console.log(`  Found ${count} tokens across ${Object.keys(byComponent).length} components`);

	writeGeneratedTokenModule(byComponent);
	syncSpecTokenTables(byComponent);

	console.log('Done!');
}

main();
